### PR TITLE
Patches for 1.101x

### PR DESCRIPTION
**Pull request by supreeth-t**
CL has the following patches onto HDP branch 'tetration' which is our hadoop release branch.

Hadoop-11333 
HDFS-5809

Onto branch tetration itself I committed HDFS-7005.

@andy256 Please review.

### CODE REVIEW

**Comment by ghost** [comment]
LGTM. Do you want to update the version number in the pom or something? Like 2.4.1.1 maybe?

**Comment by supreeth-t** [comment]
Let me increment the current version by 1 on the minor number.

**Comment by ghost** [comment]
We need to distinguish between our own builds and patches and the upstream
version though.

**Comment by supreeth-t** [comment]
Yes thats right.,

**Pull request merged**
