### PR TITLE
Patch HADOOP-11604 and HADOOP-11802

### PR DESCRIPTION
**Pull request by ghost**
Back-ported both patches to hadoop 2.4.

Unfortunately the tests for 11802 don't back-port cleanly without a lot more changes.

Running local unit test suite now.

@supreeth-t please review and test when you get a chance.

### CODE REVIEW

**Comment by supreeth-t** [comment]
LGTM, did the local tests complete?

**Comment by ghost** [comment]
no, they apparently don't work on OS X. if you have a VM / docker image handy, could you try it?

**Comment by ghost** [comment]
running w/ java 1.7 now; they're moving along just fine now... will update when they finish

**Comment by ghost** [comment]
build was successful, some random unrelated hadoop common unit test failed

**Comment by supreeth-t** [comment]
http://anvil.tetrationanalytics.com/buildstatus#T1INCX1hR5m5ep_LdVJ9Zw - Anvil build

**Comment by ghost** [comment]
@supreeth-t did this PR ever get integrated? Did we just completely forget to merge this?

**Comment by ghost** [comment]
Is this branch the -473 that was uploaded to artifactory?

**Pull request merged**
